server:
  port: 3304

spring:
  application:
    name: article-service
  profiles:
    active: test
    include: jwt

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka