server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7000/eureka


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/article/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/article/(?<segment>.*), /$\{segment}

        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/room/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/room/(?<segment>.*), /$\{segment}




