server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7000/eureka


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/member/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/email/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/article/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/image/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/amazon/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/faq/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/frame/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/room/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/participant/**
          filters:
            - RemoveRequestHeader=Cookie



