server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7000/eureka


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/member/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/email/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/login/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/logout/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/api/article/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/api/image/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/api/amazon/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/api/faq/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/api/frame/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/api/room/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/api/participant/**
          filters:
            - RemoveRequestHeader=Cookie



