spring:
  config:
    import: 'optional:configserver:/'

  port: 8600
  datasource:
    username: root
    password: qwe1234jkl7896
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://i9a401.p.ssafy.io:3307/200ok
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
      table-prefix: BATCH_
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      enabled: false
cloud:
  aws:
    s3:
      bucket: '200oks3bucket'
    credentials:
      instance-profile: false
      access-key: 'AKIA3EISLCMY36Q4S7OW'
      secret-key: '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'
    region:
      auto: false
      static: 'ap-northeast-2'
    stack:
      auto: false
