server:
  port: 8999


spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/se6816/sayCheese_config
          default-label: master