spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
cloud:
  aws:
    credentials:
      instance-profile: false
      access-key: AKIA3EISLCMYYZ5MKYEZ
      secret-key: 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
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false