server:
  port: 8080
spring:
  data:
    redis:
      host: '127.0.0.1'
      port: 6379
      password: 17171771
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
logging.level:
  org.hibernate.SQL: debug