server:
    port: 8081
spring:
  datasource:
        url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P12A401
        username: S09P12A401
        password: qyBRUweO0E
        driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
cloud:
  aws:
    credentials:
      instance-profile: false
      access-key: AKIA3EISLCMYYZ5MKYEZ
      secret-key: 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
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false